In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [2]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hs414\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [22]:
x = "you should die"
y = "I like you dream"

In [23]:
from nltk.stem.porter import PorterStemmer

In [24]:
def clean(x,voc_size = 5000,sent_length=159):
    ps = PorterStemmer()
    review = re.sub('[^a-zA-Z]',' ',x)
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    onehot_repr = [one_hot(review,voc_size)]
    embedded_x = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
    return embedded_x

In [26]:
x_clean = clean(x)
y_clean = clean(y)

In [27]:
model = tf.keras.models.load_model('ytnn.h5')

In [28]:
model.predict(x_clean)

1/1 [==============================] - 0s 305ms/step


array([[0.02553676]], dtype=float32)

In [33]:
model.predict(y_clean)

1/1 [==============================] - 0s 25ms/step


array([[0.5597731]], dtype=float32)

In [41]:
def predict(model,x):
    pred = model.predict(x)
    if pred > 0.50:
        print("The Comment is not spam")
    else:
        print("The Comment is spam")
    return pred

In [42]:
predict(model,x_clean)

1/1 [==============================] - 0s 26ms/step
The Comment is spam


array([[0.02553676]], dtype=float32)

In [43]:
predict(model,y_clean)

1/1 [==============================] - 0s 25ms/step
The Comment is not spam


array([[0.5597731]], dtype=float32)

In [49]:
stop_words = pd.DataFrame(stopwords.words('english'))

In [52]:
stop_words.to_csv("stopwords")